sonatype/nexus-oss

- plugins/rubygem/nexus-ruby-plugin/src/main/java/org/sonatype/nexus/plugins/ruby/ScriptingContainerProvider.java
- plugins/rubygem/nexus-ruby-tools/pom.xml
- plugins/rubygem/nexus-ruby-tools/src/test/minispecs/repair_helper_spec.rb
- plugins/rubygem/pom.xml
and use IsolatedScriptingContainer with its new OSGi support. which also
reduces the start up of the ScriptingContainer significantly.
please review and have a look at the startup time of ScriptingContainer
> nexus-2.11.x switch to jruby-1.7.17

- plugins/osgi/nexus-obr-plugin/src/main/java/org/osgi/impl/bundle/obr/resource/BundleInfo.java
- testsuite/modern-testsuite/pom.xml
- testsuite/modern-testsuite/src/test/java/org/sonatype/nexus/testsuite/obr/ObrIT.java
- testsuite/modern-testsuite/src/test/java/org/sonatype/nexus/testsuite/obr/ObrITSupport.java
https://issues.sonatype.org/browse/NEXUS-7873
http://bamboo.s/browse/NX-OSSF465-1 :white_check_mark:
> [NEXUS-7873] ignore 'bundle-version' attributes on Import-Package when processing OBR

- components/nexus-core/src/main/java/org/sonatype/nexus/proxy/maven/gav/M2ArtifactRecognizer.java
- components/nexus-core/src/main/java/org/sonatype/nexus/proxy/maven/maven2/M2Repository.java
- testsuite/legacy-testsuite/src/test/java/org/sonatype/nexus/testsuite/deploy/nexus2351/Nexus2351DisableRedeployMaven2IT.java
https://issues.sonatype.org/browse/NEXUS-7808
http://bamboo.s/browse/NX-OSSF473
> [NEXUS-7808] Use GAV calculator to determine if an artifact is a snapshot

- buildsupport/other/pom.xml
- components/nexus-ehcache/src/test/java/org/sonatype/sisu/ehcache/CacheManagerComponentImplTest.java
http://bamboo.s/browse/NX-OSSF475-1
> Upgrade to ehcache 2.6.9_1

- buildsupport/goodies/pom.xml
- buildsupport/other/pom.xml
- components/nexus-core/src/main/java/org/sonatype/nexus/proxy/storage/remote/httpclient/HttpClientRemoteStorage.java
- plugins/basic/nexus-content-plugin/src/main/java/org/sonatype/nexus/content/internal/ContentServlet.java
- testsuite/modern-testsuite/src/test/java/org/sonatype/nexus/testsuite/routing/RoutingSanityIT.java
Depends on https://github.com/sonatype/sisu-goodies/pull/31
http://bamboo.s/browse/NX-OSSF478-1
> Bump Guava to 18.0

- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/model/Role.js
- update the ExtJS model with an appropriate sorter and enhance existing functional test to confirm behaviour
> NEXUS-7883 - Role ordering now case sensitive

- components/nexus-core/src/main/java/org/sonatype/nexus/security/filter/authc/NexusHttpAuthenticationFilter.java
https://issues.sonatype.org/browse/NEXUS-7949
http://bamboo.s/browse/NX-OSSF506
> [NEXUS-7949] User is logged in also if is remembered

- plugins/basic/nexus-site-repository-plugin/src/main/java/org/sonatype/nexus/repository/site/plugin/DefaultSiteRepository.java
- testsuite/modern-testsuite/src/test/it-resources/org/sonatype/nexus/testsuite/site/site-2/pom.xml
- testsuite/modern-testsuite/src/test/it-resources/org/sonatype/nexus/testsuite/site/site-2/src/main/resources/readme.txt
- testsuite/modern-testsuite/src/test/java/org/sonatype/nexus/testsuite/site/SiteRepositoryIT.java
https://issues.sonatype.org/browse/NEXUS-7929
http://bamboo.s/browse/NX-OSSF507-1 :white_check_mark:
> NEXUS-7929: normalize deploy requests to site repositories

- plugins/rubygem/nexus-ruby-tools/src/main/java/org/sonatype/nexus/ruby/layout/HostedDELETELayout.java
this should fix https://issues.sonatype.org/browse/NEXUS-7927
> delete rubygems file AFTER closing existing read stream on it

- components/nexus-core/src/main/java/org/sonatype/nexus/proxy/wastebasket/DefaultWastebasket.java
Makes possible to disable repository item trash completely.
By setting 
`org.sonatype.nexus.proxy.wastebasket.DefaultWastebasket.defaultDeleteOperation`
system property to `DELETE_PERMANENTLY` trash will be deactivated, and permanent deletions will be used in case of item delete operations.
CI
http://bamboo.s/browse/NX-OSSF498
> Add property to expose default delete operation

- assemblies/nexus-base-edition/src/main/feature/feature.xml
- buildsupport/db/pom.xml
http://bamboo.s/browse/NX-OSSF510-1
> Upgrade to OrientDB 2.0

- buildsupport/other/pom.xml
- components/nexus-mime/src/main/resources/org/apache/tika/mime/custom-mimetypes.xml
And remove the "hack" for MS PE files (see NEXUS-7603)
Issue
https://issues.sonatype.org/browse/NEXUS-7650
CI
http://bamboo.s/browse/NX-OSSF509
> NEXUS-7650: Update to tika 1.7

- components/nexus-core/src/main/java/org/sonatype/nexus/maven/tasks/RebuildMavenMetadataTaskDescriptor.java
- components/nexus-core/src/main/java/org/sonatype/nexus/maven/tasks/ReleaseRemovalTaskDescriptor.java
- components/nexus-core/src/main/java/org/sonatype/nexus/maven/tasks/SnapshotRemovalTaskDescriptor.java
- components/nexus-core/src/main/java/org/sonatype/nexus/maven/tasks/UnusedSnapshotRemoverTaskDescriptor.java
- components/nexus-core/src/main/java/org/sonatype/nexus/tasks/EmptyTrashTaskDescriptor.java
- components/nexus-core/src/main/java/org/sonatype/nexus/tasks/EvictUnusedProxiedItemsTaskDescriptor.java
- components/nexus-core/src/main/java/org/sonatype/nexus/tasks/ExpireCacheTaskDescriptor.java
- components/nexus-core/src/main/java/org/sonatype/nexus/tasks/RebuildAttributesTaskDescriptor.java
- components/nexus-core/src/main/java/org/sonatype/nexus/tasks/SynchronizeShadowTaskDescriptor.java
- plugins/basic/nexus-timeline-plugin/src/main/java/org/sonatype/nexus/timeline/tasks/PurgeTimelineTaskDescriptor.java
- plugins/indexer/nexus-indexer-lucene-plugin/src/main/java/org/sonatype/nexus/index/tasks/descriptors/AbstractIndexTaskDescriptor.java
- plugins/indexer/nexus-indexer-lucene-plugin/src/main/java/org/sonatype/nexus/index/tasks/descriptors/DownloadIndexesTaskDescriptor.java
- plugins/indexer/nexus-indexer-lucene-plugin/src/main/java/org/sonatype/nexus/index/tasks/descriptors/OptimizeIndexTaskDescriptor.java
- plugins/indexer/nexus-indexer-lucene-plugin/src/main/java/org/sonatype/nexus/index/tasks/descriptors/PublishIndexesTaskDescriptor.java
- plugins/p2/nexus-p2-repository-plugin/src/main/java/org/sonatype/nexus/plugins/p2/repository/internal/tasks/P2MetadataGeneratorTaskDescriptor.java
- plugins/p2/nexus-p2-repository-plugin/src/main/java/org/sonatype/nexus/plugins/p2/repository/internal/tasks/P2RepositoryAggregatorTaskDescriptor.java
- plugins/p2/nexus-p2-repository-plugin/src/main/java/org/sonatype/nexus/plugins/p2/repository/updatesite/UpdateSiteMirrorTaskDescriptor.java
- plugins/yum/nexus-yum-repository-plugin/src/main/java/org/sonatype/nexus/yum/internal/task/GenerateMetadataTaskDescriptor.java
Changes:
* EmptyTrashTask helper text change
* Aligned with design principles by removing period on single sentence texts
* source reformat where needed, no other code change
Issue
https://issues.sonatype.org/browse/NEXUS-7895
CI
TBD
> NEXUS-7895: Sweep changes of task descriptors

- buildsupport/httpclient/pom.xml
Update HttpClient and HttpCore to:
HttpClient 4.3.6, release notes
HttpCore 4.3.3, release notes
Issue
https://issues.sonatype.org/browse/NEXUS-7995
CI
http://bamboo.s/browse/NX-OSSF527
> NEXUS-7995: Bump HttpClient et al

- buildsupport/httpclient/pom.xml
Update HttpClient and HttpCore to:
* HttpClient 4.3.6, [release notes](https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12310360&version=12327489)
* HttpCore 4.3.3, [release notes](https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12310340&version=12326260)
Issue
https://issues.sonatype.org/browse/NEXUS-7995
CI
http://bamboo.s/browse/NX-OSSF526
> NEXUS-7995: Bump HttpClient et al. (2.11.x)

- assemblies/nexus-base-template/pom.xml
- buildsupport/logging/pom.xml
- buildsupport/osgi/pom.xml
- pom.xml
Karaf 3.0.3 is staged, but not yet released (voting is in progress). These are the changes I used to test the staged release locally. List of fixes in this patch release: http://svn.apache.org/viewvc/karaf/site/trunk/src/main/webapp/index/community/download/karaf-3.0.3-release.page?view=markup
> Upgrade to Karaf 3.0.3

- plugins/npm/pom.xml
https://github.com/orientechnologies/orientdb/issues?q=milestone%3A2.0.1
http://bamboo.s/browse/NX-OSSF551-1/ :white_check_mark:
> [nexus-2.11.x] Upgrade to OrientDB 2.0.1 hotfix

- buildsupport/db/pom.xml
https://github.com/orientechnologies/orientdb/issues?q=milestone%3A2.0.1
http://bamboo.s/browse/NX-OSSF550-1/ :white_check_mark:
> Upgrade to OrientDB 2.0.1 hotfix

- plugins/rapture/nexus-rapture-plugin/src/main/resources/static/rapture/NX/view/drilldown/Drilldown.js
Issue: https://issues.sonatype.org/browse/NEXUS-8117
> [NEXUS-8117] Fixes intermittent problem with drilldown

- buildsupport/httpclient/pom.xml
- components/nexus-core/src/main/java/org/sonatype/nexus/internal/httpclient/HttpClientFactoryImpl.java
And remove workarounds for bugs fixed in this release.
Issue
https://issues.sonatype.org/browse/NEXUS-8066
CI
http://bamboo.s/browse/NX-OSSF559
> NEXUS-8066: Update HttpClient to 4.4

- plugins/npm/pom.xml
CI
http://bamboo.s/browse/NX-OSSF569
> Update to OrientDB 2.0.2 hotfix

- plugins/npm/nexus-npm-repository-plugin/src/main/java/com/bolyuba/nexus/plugin/npm/service/internal/orient/OrientMetadataStore.java
- plugins/npm/nexus-npm-repository-plugin/src/main/java/com/bolyuba/nexus/plugin/npm/service/internal/orient/PackageRootHandler.java
as it's used in several queries, see https://issues.sonatype.org/browse/NEXUS-8039 for the performance advice
http://bamboo.s/browse/NX-OSSF545-1
> NEXUS-8039: add index for NPM repositoryId property

- buildsupport/guice/pom.xml
https://wiki.eclipse.org/Sisu/Changelog#Release_0.3.0
http://bamboo.s/browse/NX3-OSSF37-1
> Update to Eclipse/Sisu 0.3.0 (also pull in latest Sisu/Guice build)

- plugins/basic/nexus-ui-extjs3-plugin/src/main/resources/static/js/repoServer/RepoServer.js
As it performs badly on external realms.
Issue
https://issues.sonatype.org/browse/NEXUS-8070
> NEXUS-8070: Remove of forgotId and forgotPw

- buildsupport/jetty/pom.xml
CI
http://bamboo.s/browse/NX-OSSF596
> [2.x] Update Jetty to 8.1.16.v20140903

- buildsupport/jetty/pom.xml
CI
http://bamboo.s/browse/NX3-OSSF44
> Update Jetty 9.2.9.v20150224

- components/nexus-core/src/main/java/org/sonatype/nexus/proxy/registry/DefaultRepositoryTypeRegistry.java
and remove leftover repoCachedContentClasses
http://bamboo.s/browse/NX3-OSSF48-1 :white_check_mark:
> Fix getRepositoryContentClass

- plugins/rubygem/nexus-ruby-plugin/src/main/java/org/sonatype/nexus/plugins/ruby/PurgeBrokenFilesRubygemsWalkerProcessor.java
- plugins/rubygem/nexus-ruby-plugin/src/main/java/org/sonatype/nexus/plugins/ruby/hosted/DefaultHostedRubyRepository.java
- plugins/rubygem/nexus-ruby-plugin/src/main/java/org/sonatype/nexus/plugins/ruby/hosted/RebuildRubygemsMetadataTaskDescriptor.java
- plugins/rubygem/nexus-ruby-plugin/src/main/java/org/sonatype/nexus/plugins/ruby/hosted/RecreateIndexRubygemsWalkerProcessor.java
- plugins/rubygem/nexus-ruby-plugin/src/main/java/org/sonatype/nexus/plugins/ruby/proxy/DefaultProxyRubyRepository.java
- plugins/rubygem/nexus-ruby-plugin/src/main/java/org/sonatype/nexus/plugins/ruby/proxy/PurgeBrokenRubygemsMetadataTaskDescriptor.java
- plugins/rubygem/nexus-ruby-plugin/src/main/java/org/sonatype/nexus/plugins/ruby/proxy/SyncRubygemsMetadataTaskDescriptor.java
- plugins/rubygem/nexus-ruby-tools/src/main/java/org/sonatype/nexus/ruby/SpecsHelper.java
- plugins/rubygem/nexus-ruby-tools/src/main/resources/nexus/specs_helper_impl.rb
- plugins/rubygem/nexus-ruby-tools/src/test/java/org/sonatype/nexus/ruby/SpecsHelperTest.java
- testsuite/modern-testsuite/src/test/java/org/sonatype/nexus/testsuite/ruby/GemLifecycleIT.java
- testsuite/modern-testsuite/src/test/java/org/sonatype/nexus/testsuite/ruby/RubyITSupport.java
WIP
tested manually but UTs are broken and ITs for this implementation is missing.
> NEXUS-8114: Rubygems reindexing problem

- components/nexus-core/src/test/java/org/sonatype/nexus/AbstractMavenRepoContentTests.java
- components/nexus-core/src/test/java/org/sonatype/nexus/NexusAppTestSupport.java
- components/nexus-core/src/test/java/org/sonatype/nexus/internal/log/LogbackLogManagerTest.java
- components/nexus-core/src/test/java/org/sonatype/nexus/proxy/AbstractProxyTestEnvironment.java
- components/nexus-core/src/test/java/org/sonatype/nexus/proxy/M1LayoutedM2ShadowRepositoryTest.java
- components/nexus-core/src/test/java/org/sonatype/nexus/proxy/M2LayoutedM1ShadowRepositoryTest.java
- components/nexus-core/src/test/java/org/sonatype/nexus/proxy/mapping/PathBasedRequestRepositoryMapperTest.java
- components/nexus-core/src/test/java/org/sonatype/nexus/proxy/registry/DefaultRepositoryRegistryTest.java
- plugins/indexer/nexus-indexer-lucene-plugin/pom.xml
- plugins/indexer/nexus-indexer-lucene-plugin/src/test/java/org/sonatype/nexus/IndexCreatorHelper.java
- plugins/indexer/nexus-indexer-lucene-plugin/src/test/java/org/sonatype/nexus/ReindexIT.java
- plugins/indexer/nexus-indexer-lucene-plugin/src/test/java/org/sonatype/nexus/index/AbstractIndexerManagerTest.java
- plugins/maven/nexus-archetype-plugin/pom.xml
- plugins/maven/nexus-archetype-plugin/src/test/java/org/sonatype/nexus/plugins/mac/AbstractMacPluginTest.java
- plugins/maven/nexus-archetype-plugin/src/test/java/org/sonatype/nexus/plugins/mac/MacPluginEventSubscriberIT.java
- plugins/maven/nexus-maven-bridge-plugin/pom.xml
- plugins/maven/nexus-maven-bridge-plugin/src/test/java/org/sonatype/nexus/plugins/mavenbridge/MavenBridgeIT.java
- plugins/maven/nexus-maven-bridge-plugin/src/test/java/org/sonatype/nexus/plugins/mavenbridge/ResolvingIT.java
- plugins/p2/nexus-p2-repository-plugin/src/test/java/org/sonatype/nexus/plugins/p2/repository/P2ProxyMirrorsTest.java
- plugins/security/nexus-kenai-plugin/src/test/java/org/sonatype/nexus/kenai/AbstractKenaiRealmTest.java
- plugins/security/nexus-ldap-plugin/src/test/java/org/sonatype/nexus/ldap/internal/LdapTestSupport.java
- plugins/yum/nexus-yum-repository-plugin/src/test/java/org/sonatype/nexus/yum/internal/support/YumNexusTestSupport.java
- testsupport/nexus-plugin-testsupport/src/main/java/org/sonatype/nexus/AbstractPluginTestCase.java
- testsupport/nexus-test-common/pom.xml
- testsupport/nexus-test-common/src/main/java/org/sonatype/nexus/test/NexusTestSupport.java
http://bamboo.s/browse/NX3-OSSF54-1 :white_check_mark:
> Remove Plexus from majority of tests

- plugins/npm/pom.xml
See https://github.com/sonatype/nexus-oss/pull/1072
http://bamboo.s/browse/NX-OSSF612-1 :white_check_mark:
> Update OrientDB to 2.0.4

- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/controller/Search.js
> Set search breadcrumb through the feature, not the drilldown

- components/nexus-core/src/main/java/org/sonatype/nexus/tasks/ReconcileChecksumsTask.java
Followup improvements as requested in https://issues.sonatype.org/browse/NEXUS-8226
> Reconcile checksum improvements

- assemblies/nexus-base-template/src/main/resources/overlay/etc/system.properties
https://issues.sonatype.org/browse/NEXUS-7678
> [NEXUS-7678] Set karaf.history location to ~/.nexus/karaf.history

- components/nexus-orient/src/main/java/org/sonatype/nexus/orient/entity/SingletonEntityAdapter.java
> Use orient 'dictionary' index to manage singleton record

- plugins/basic/nexus-repository-nuget/README.md
https://issues.sonatype.org/browse/NEXUS-8246
> Nuget demo URLs now escaped for bash

- assemblies/nexus-base-template/pom.xml
- assemblies/nexus-base-template/src/main/resources/overlay/etc/config.properties
https://issues.sonatype.org/browse/NEXUS-7791
> [NEXUS-7791] remove xercesImpl from distribution

- plugins/basic/nexus-repository-nuget/src/main/java/com/sonatype/nexus/repository/nuget/internal/NugetGalleryFacetImpl.java
- plugins/basic/nexus-repository-nuget/src/main/java/com/sonatype/nexus/repository/nuget/internal/proxy/NugetProxyGalleryFacet.java
https://issues.sonatype.org/browse/NEXUS-8258
https://issues.sonatype.org/browse/NEXUS-8259
> Nexus 8258 nexus 8259 nuget fixes

- components/nexus-orient/src/main/java/org/sonatype/nexus/orient/graph/GraphTx.java
- components/nexus-repository/src/main/java/org/sonatype/nexus/repository/storage/StorageFacetImpl.java
- plugins/basic/nexus-repository-nuget/src/main/java/com/sonatype/nexus/repository/nuget/internal/NugetGalleryFacetImpl.java
- plugins/basic/nexus-repository-nuget/src/test/java/com/sonatype/nexus/repository/nuget/internal/NugetGalleryFacetImplPutTest.java
- plugins/basic/nexus-repository-raw/src/main/java/org/sonatype/nexus/repository/raw/internal/RawContentFacetImpl.java
https://issues.sonatype.org/browse/NEXUS-8260
> [NEXUS-8260] Automatically set last_updated for assets/components

- components/nexus-blobstore-api/src/main/java/org/sonatype/nexus/blobstore/api/BlobStore.java
- components/nexus-blobstore-api/src/main/java/org/sonatype/nexus/blobstore/api/BlobStoreConfiguration.java
- components/nexus-blobstore-file/src/main/java/org/sonatype/nexus/blobstore/file/FileBlobStore.java
- components/nexus-blobstore-file/src/main/java/org/sonatype/nexus/blobstore/file/SimpleFileOperations.java
- components/nexus-blobstore-file/src/main/java/org/sonatype/nexus/blobstore/file/VolumeChapterLocationStrategy.java
- components/nexus-core/src/main/java/org/sonatype/nexus/internal/blobstore/BlobStoreConfigurationEntityAdapter.java
- components/nexus-core/src/main/java/org/sonatype/nexus/internal/blobstore/BlobStoreManagerImpl.java
- components/nexus-core/src/test/java/org/sonatype/nexus/internal/blobstore/BlobStoreConfigurationStoreImplTest.groovy
- components/nexus-core/src/test/java/org/sonatype/nexus/internal/blobstore/BlobStoreManagerImplTest.groovy
- plugins/rapture/nexus-coreui-plugin/src/main/java/org/sonatype/nexus/coreui/BlobStoreComponent.groovy
Allow for additional future BlobStore types
> refactor blobstore creation by provider

- components/nexus-repository/src/main/java/org/sonatype/nexus/repository/group/GroupHandler.java
- components/nexus-repository/src/main/java/org/sonatype/nexus/repository/proxy/ProxyHandler.java
- plugins/basic/nexus-repository-httpbridge/src/main/java/org/sonatype/nexus/repository/httpbridge/DefaultHttpResponseSender.java
- plugins/basic/nexus-repository-httpbridge/src/main/java/org/sonatype/nexus/repository/httpbridge/HttpResponseSender.java
- plugins/basic/nexus-repository-httpbridge/src/main/java/org/sonatype/nexus/repository/httpbridge/internal/ViewServlet.java
- plugins/basic/nexus-repository-httpbridge/src/test/java/org/sonatype/nexus/repository/httpbridge/internal/ViewServletDescribeTest.java
- plugins/basic/nexus-repository-raw/src/main/java/org/sonatype/nexus/repository/raw/internal/RawContentHandler.java
- plugins/basic/nexus-repository-simple/src/main/java/org/sonatype/nexus/repository/simple/internal/SimpleIndexHtmlHandler.java
- plugins/basic/nexus-repository-simple/src/main/java/org/sonatype/nexus/repository/simple/internal/SimpleProxyHandler.java
- plugins/basic/nexus-repository-simple/src/main/java/org/sonatype/nexus/repository/simple/internal/SimpleStorageHandler.java
Issue
https://issues.sonatype.org/browse/NEXUS-8281
> NEXUS-8281: HEAD support in sender and some crucial Handlers

- plugins/basic/nexus-repository-maven/src/main/java/org/sonatype/nexus/repository/maven/internal/MavenDefaultRepositoriesContributor.groovy
- hosted only, one repo for releases and one for snapshots
https://issues.sonatype.org/browse/NEXUS-8294
Feedback on names is appreciated :)
> NEXUS-8294 - Add Maven default repos

- plugins/basic/nexus-repository-httpbridge/src/main/java/org/sonatype/nexus/repository/httpbridge/DefaultHttpResponseSender.java
- plugins/basic/nexus-repository-maven/src/main/java/org/sonatype/nexus/repository/maven/internal/MavenFacet.java
- plugins/basic/nexus-repository-maven/src/main/java/org/sonatype/nexus/repository/maven/internal/MavenFacetImpl.java
- plugins/basic/nexus-repository-maven/src/main/java/org/sonatype/nexus/repository/maven/internal/MavenHeadersHandler.java
- plugins/basic/nexus-repository-maven/src/main/java/org/sonatype/nexus/repository/maven/internal/MavenPayload.java
- plugins/basic/nexus-repository-maven/src/main/java/org/sonatype/nexus/repository/maven/internal/maven2/Maven2HostedRecipe.groovy
This change undos the BlobPayload "spice" stuff, already present in master, brought in by Maven CMA Hosted PR.
> Undo BlobPayload "spice" changes

- buildsupport/httpclient/pom.xml
Seems should solve the retries problem
See
https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12310360&version=12329394
CI
http://bamboo.s/browse/NX3-OSSF137
> Bump to HttpClient 4.4.1

- plugins/basic/nexus-repository-nuget/pom.xml
- plugins/basic/nexus-repository-nuget/src/main/java/com/sonatype/nexus/repository/nuget/internal/security/NugetApiKeyComponent.groovy
- plugins/basic/nexus-repository-nuget/src/main/java/com/sonatype/nexus/repository/nuget/internal/security/NugetApiKeyStoreImpl.java
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/app/PluginConfig.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/app/PluginStrings.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/controller/NuGetApiKey.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/view/nuget/NuGetApiKey.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/view/nuget/NuGetApiKeyDetails.js
- utilizes existing UI elements from nexus-nuget-plugin and moves the functionality to the user feature in the UI
Present nexus pro UI for this functionality adds a tab to each nuget repo: http://screencast.com/t/3iGWR6aBQE
Proposed change puts this under the User's account management: http://screencast.com/t/0AFKmHZsDucV
> NEXUS-8287 NuGet api key ui

- components/nexus-repository/src/main/java/org/sonatype/nexus/repository/group/GroupFacetImpl.java
https://issues.sonatype.org/browse/NEXUS-8016
> NEXUS-8016 Group member compatibility

- components/nexus-core/src/main/java/org/sonatype/nexus/internal/security/model/CPrivilegeEntityAdapter.java
- components/nexus-core/src/main/java/org/sonatype/nexus/internal/security/model/CRoleEntityAdapter.java
- components/nexus-core/src/main/java/org/sonatype/nexus/internal/security/model/CUserEntityAdapter.java
- components/nexus-core/src/main/java/org/sonatype/nexus/internal/security/model/CUserRoleMappingEntityAdapter.java
- components/nexus-repository/src/main/java/org/sonatype/nexus/repository/storage/MetadataNodeEntityAdapter.java
- plugins/basic/nexus-repository-nuget/src/main/java/com/sonatype/nexus/repository/nuget/internal/security/NugetApiKeyEntityAdapter.java
- plugins/security/nexus-ldap-plugin/src/main/java/org/sonatype/nexus/ldap/internal/persist/orient/LdapConfigurationEntityAdapter.java
- plugins/yum/nexus-yum-repository-plugin/src/main/java/org/sonatype/nexus/yum/internal/createrepo/YumPackageEntityAdapter.java
http://bamboo.s/browse/NX3-OSSF175
> Use OIndexNameBuilder

- components/nexus-blobstore-api/src/main/java/org/sonatype/nexus/blobstore/api/BlobStore.java
- components/nexus-blobstore-file/src/main/java/org/sonatype/nexus/blobstore/file/FileBlobStore.java
- components/nexus-blobstore-file/src/test/java/org/sonatype/nexus/blobstore/file/FileBlobStoreTest.java
https://issues.sonatype.org/browse/NEXUS-8234
This turned out way simpler than I imagined. Unsure if we need to make some sort of Visitor for it, but I figure that can wait until it's obvious.
> NEXUS-8234 - Blob iteration

- components/nexus-core/src/main/java/org/sonatype/nexus/internal/security/StaticSecurityConfigurationResourceImpl.groovy
- plugins/rapture/nexus-coreui-plugin/src/main/java/org/sonatype/nexus/coreui/UserComponent.groovy
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/app/PluginStrings.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/controller/Users.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/view/user/UserFeature.js
https://issues.sonatype.org/browse/NEXUS-8429
> [NEXUS-8429] Rip out remaining user password "reset" bits from UI/backend

- components/nexus-core/src/main/filtered-resources/META-INF/nexus/default-oss-nexus.xml
- components/nexus-core/src/test/filtered-resources/META-INF/nexus/nexus.xml
- components/nexus-core/src/test/java/org/sonatype/nexus/NexusAppTestSupportSecurity.groovy
- components/nexus-oss-edition/src/main/filtered-resources/META-INF/nexus/nexus.xml
- components/nexus-security/src/main/java/org/sonatype/nexus/security/config/StaticSecurityConfigurationSource.groovy
- components/nexus-security/src/test/java/org/sonatype/nexus/security/BaseSecurityConfig.groovy
- components/nexus-security/src/test/java/org/sonatype/nexus/security/authz/AuthorizationManagerTestSecurity.groovy
- components/nexus-security/src/test/java/org/sonatype/nexus/security/user/AdditionalRoleSecuritySystemTestSecurity.groovy
- components/nexus-security/src/test/java/org/sonatype/nexus/security/user/EmptyRoleManagementTestSecurity.groovy
- components/nexus-security/src/test/java/org/sonatype/nexus/security/user/MissingRoleUserManagerTestSecurity.groovy
- components/nexus-security/src/test/java/org/sonatype/nexus/security/user/UserManager2Test.java
- components/nexus-security/src/test/java/org/sonatype/nexus/security/user/UserManager2TestSecurity.groovy
- components/nexus-security/src/test/java/org/sonatype/nexus/security/user/UserManagerTest.java
- components/nexus-security/src/test/java/org/sonatype/nexus/security/user/UserManagerTestSecurity.groovy
- components/nexus-security/src/test/java/org/sonatype/nexus/security/user/UserRoleMappingTest.java
- components/nexus-security/src/test/java/org/sonatype/nexus/security/user/UserRoleMappingTestSecurity.groovy
https://issues.sonatype.org/browse/NEXUS-7862
related:
* https://github.com/sonatype/nexus-pro/pull/524
* https://github.com/sonatype/nexus-bundles/pull/137
> [NEXUS-7862] Update all email addresses in default/test -> @example.org

- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/view/system/VerifySMTPConnection.js
https://issues.sonatype.org/browse/NEXUS-8484
> [NEXUS-8484] blur on validate for smtp verify dialog form

- components/nexus-repository/src/main/java/org/sonatype/nexus/repository/storage/StorageFacetImpl.java
- plugins/basic/nexus-repository-maven/src/main/java/org/sonatype/nexus/repository/maven/internal/MavenDefaultRepositoriesContributor.groovy
- plugins/basic/nexus-repository-nuget/src/main/java/com/sonatype/nexus/repository/nuget/internal/NugetDefaultRepositoriesContributor.groovy
https://issues.sonatype.org/browse/NEXUS-8495
The fix is to make write policy mandatory for hosted repos and set the value for default repositories
> [NEXUS-8495] Make write policy mandatory for hosted repositories

- components/nexus-common/src/main/java/org/sonatype/nexus/common/entity/Entity.java
- components/nexus-common/src/main/java/org/sonatype/nexus/common/entity/EntityId.java
- components/nexus-orient/src/main/java/org/sonatype/nexus/orient/entity/EntityAdapter.java
- components/nexus-repository/src/main/java/org/sonatype/nexus/repository/storage/AssetEntityAdapter.java
- components/nexus-repository/src/main/java/org/sonatype/nexus/repository/storage/MetadataNode.java
- components/nexus-repository/src/main/java/org/sonatype/nexus/repository/storage/MetadataNodeEntityAdapter.java
- components/nexus-repository/src/main/java/org/sonatype/nexus/repository/storage/StorageTxImpl.java
- components/nexus-repository/src/test/java/org/sonatype/nexus/repository/storage/StorageFacetImplIT.java
https://issues.sonatype.org/browse/NEXUS-8509
> StorageTx Fixes

- components/nexus-repository/src/main/java/org/sonatype/nexus/repository/httpclient/NtlmAuthenticationConfig.java
- components/nexus-repository/src/main/java/org/sonatype/nexus/repository/httpclient/UsernameAuthenticationConfig.java
- components/nexus-repository/src/test/java/org/sonatype/nexus/repository/httpclient/HttpClientConfigValidationTest.groovy
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/view/repository/facet/HttpFacet.js
Require password in all cases, authentication details can be removed on update by de-selecting the Authentication fieldset.
https://issues.sonatype.org/browse/NEXUS-8502
+1 by CI http://bamboo.s/browse/NX3-OSSF244-2
> NEXUS-8502 password required

- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/app/PluginStrings.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/controller/Log.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/view/logging/LogMark.js
https://issues.sonatype.org/browse/NEXUS-8441
> [NEXUS-8441] Mask entire screen when marking log

- components/nexus-core/src/main/java/org/sonatype/nexus/proxy/storage/local/fs/DefaultFSLocalRepositoryStorage.java
slight optimization by avoiding duplicate File.lastModified()
> slight optimization by avoiding duplicate File.lastModified()

- plugins/rapture/nexus-rapture-plugin/src/main/resources/static/rapture/NX/State.js
- plugins/rapture/nexus-rapture-plugin/src/main/resources/static/rapture/NX/app/PluginStrings.js
- plugins/rapture/nexus-rapture-plugin/src/main/resources/static/rapture/NX/controller/ExtDirect.js
- plugins/rapture/nexus-rapture-plugin/src/main/resources/static/rapture/NX/controller/UiSessionTimeout.js
- plugins/rapture/nexus-rapture-plugin/src/main/resources/static/rapture/NX/controller/User.js
https://issues.sonatype.org/browse/NEXUS-8157
http://bamboo.s/browse/NX3-OSSF248-1
> NEXUS-8157 timeout and disconnect

- plugins/npm/nexus-npm-repository-plugin/src/main/java/com/bolyuba/nexus/plugin/npm/service/internal/orient/EntityHandlerSupport.java
- plugins/npm/nexus-npm-repository-plugin/src/main/java/com/bolyuba/nexus/plugin/npm/service/internal/orient/PackageRootHandler.java
https://issues.sonatype.org/browse/NEXUS-8568?focusedCommentId=313542
http://bamboo.s/browse/NX-OSSF832-1
> [nexus-2.11.x] [NEXUS-8568] add NPM index to existing db

- plugins/security/nexus-ldap-plugin/src/main/java/org/sonatype/nexus/ldap/internal/ui/LdapServerComponent.groovy
https://issues.sonatype.org/browse/NEXUS-8605
> [NEXUS-8605] Fix ldap server password placeholder replacement

- components/nexus-repository/src/main/java/org/sonatype/nexus/repository/security/SecurityFacetSupport.java
https://issues.sonatype.org/browse/NEXUS-8589
> [NEXUS-8589] Add mapping of HttpMethods.MKCOL to BreadActions.ADD

- LICENSE.txt
- NOTICE.txt
https://issues.sonatype.org/browse/NEXUS-8343
related:
https://github.com/sonatype/nexus-bundles/pull/148
> [NEXUS-8343] expose OSS license details

- components/nexus-httpclient/src/main/java/org/sonatype/nexus/httpclient/config/ConfigurationCustomizer.java
- components/nexus-httpclient/src/main/java/org/sonatype/nexus/httpclient/config/ConnectionConfiguration.java
https://issues.sonatype.org/browse/NEXUS-8582
> [NEXUS-8582] Restore SSL config/setup

- components/nexus-repository/src/main/java/org/sonatype/nexus/repository/httpclient/HttpClientFacetImpl.java
Somehow related https://issues.sonatype.org/browse/NEXUS-8488
> [NEXUS-8488] Recreate repository http client when global http config change

- plugins/npm/nexus-npm-repository-plugin/src/main/java/com/bolyuba/nexus/plugin/npm/service/internal/GeneratorSupport.java
- plugins/npm/nexus-npm-repository-plugin/src/main/java/com/bolyuba/nexus/plugin/npm/service/tarball/TarballRequest.java
...as long as the version you want is complete
https://issues.sonatype.org/browse/NEXUS-8625
http://bamboo.s/browse/NX-OSSF851-1 :white_check_mark:
> nexus-2.11.x [NEXUS-8625] Should still be able to fetch tarballs from packages with incomplete version(s)

- components/nexus-httpclient/src/main/java/org/sonatype/nexus/httpclient/config/ConfigurationCustomizer.java
- plugins/rapture/nexus-coreui-plugin/src/main/java/org/sonatype/nexus/coreui/HttpSettingsXO.groovy
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/app/PluginStrings.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/view/repository/facet/HttpClientFacet.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/view/system/HttpRequestSettings.js
https://issues.sonatype.org/browse/NEXUS-8601
> [NEXUS-8601] Remove url parameters setting

- testsuite/modern-testsuite/pom.xml
- testsuite/modern-testsuite/src/test/java/org/sonatype/nexus/testsuite/security/SimpleSessionCookieIT.java
CI
http://bamboo.s/browse/NX3-OSSF332
> Fix for SimpleSessionCookieIT

- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/controller/SslTrustStore.js
- plugins/security/nexus-ssl-plugin/src/main/java/com/sonatype/nexus/ssl/plugin/internal/CertificateRetriever.java
- plugins/security/nexus-ssl-plugin/src/main/java/com/sonatype/nexus/ssl/plugin/internal/ui/CertificateComponent.groovy
https://issues.sonatype.org/browse/NEXUS-8640
> [NEXUS-8640] Fix retrieval of SSL certificates

- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/controller/HealthCheckSearch.js
https://issues.sonatype.org/browse/NEXUS-8695
> [NEXUS-8695] Do not load health check columns if permission is not granted

- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/view/repository/facet/StorageFacetHosted.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/view/repository/recipe/RawHosted.js
https://issues.sonatype.org/browse/NEXUS-8677
> NEXUS-8677: Raw repository defaults to allow redeploy

- plugins/basic/nexus-repository-httpbridge/src/main/java/org/sonatype/nexus/repository/httpbridge/internal/HttpResponseSenderSelector.java
- plugins/basic/nexus-repository-httpbridge/src/main/java/org/sonatype/nexus/repository/httpbridge/internal/ViewServlet.java
- plugins/basic/nexus-repository-httpbridge/src/test/java/org/sonatype/nexus/repository/httpbridge/internal/ViewServletDescribeTest.java
To simplify code and testing
CI
http://bamboo.s/browse/NX3-OSSF354
> Pull out senders from view servlet

- components/nexus-security/src/main/java/org/sonatype/nexus/security/SecuritySystem.java
- components/nexus-security/src/main/java/org/sonatype/nexus/security/internal/DefaultSecuritySystem.java
- components/nexus-security/src/main/java/org/sonatype/nexus/security/role/RolesExistValidator.java
- components/nexus-security/src/main/java/org/sonatype/nexus/security/role/UniqueRoleIdValidator.java
- components/nexus-security/src/main/java/org/sonatype/nexus/security/user/UniqueUserIdValidator.java
https://issues.sonatype.org/browse/NEXUS-8707
https://issues.sonatype.org/browse/NEXUS-8708
https://issues.sonatype.org/browse/NEXUS-8709
> Use Nexus realm (default auth/user managers) to check user/role uniques and existence.

- plugins/npm/nexus-npm-repository-plugin/src/main/java/com/bolyuba/nexus/plugin/npm/service/internal/orient/PackageRootHandler.java
https://issues.sonatype.org/browse/NEXUS-8737
http://bamboo.s/browse/NX-OSSF934-1 :white_check_mark:
> nexus-2.11.x [NEXUS-8737] Re-use existing ORecordBytes instead of creating a new record each time

- components/nexus-core/src/main/java/org/sonatype/nexus/internal/httpclient/DefaultsCustomizer.java
- plugins/rapture/nexus-coreui-plugin/src/main/java/org/sonatype/nexus/coreui/HttpSettingsXO.groovy
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/app/PluginStrings.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/view/system/HttpRequestSettings.js
- plugins/security/nexus-ldap-plugin/src/main/java/org/sonatype/nexus/ldap/internal/ui/LdapServerConnectionXO.groovy
https://issues.sonatype.org/browse/NEXUS-8711
> [NEXUS-8711] Timeout related

- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/app/PluginConfig.js
https://issues.sonatype.org/browse/NEXUS-8585
For now, until we can sort out how timeline/feeds works in the larger scope of NX3.
> [NEXUS-8585] Disable Feeds UI for now

- components/nexus-core/src/main/java/org/sonatype/nexus/internal/blobstore/BlobStoreManagerImpl.java
- components/nexus-core/src/test/java/org/sonatype/nexus/internal/blobstore/BlobStoreManagerImplTest.groovy
https://issues.sonatype.org/browse/NEXUS-8762
http://bamboo.s/browse/NX3-OSSF396-1 :white_check_mark:
> [NEXUS-8762] rollback invalid BlobStore configurations

- components/nexus-common/src/main/java/org/sonatype/nexus/common/io/TempStreamSupplier.java
https://issues.sonatype.org/browse/NEXUS-8799
http://bamboo.s/browse/NX3-OSSF412-1 :white_check_mark:
> [NEXUS-8799] remember to close stream after we've copied it

- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/app/PluginStrings.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/view/task/TaskAdd.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/view/task/TaskSettingsForm.js
https://issues.sonatype.org/browse/NEXUS-8783
> [NEXUS-8783] Set proper editable condition for tasks

- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/view/repository/RepositorySettingsForm.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/view/repository/facet/StorageFacet.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/view/repository/facet/StorageFacetHosted.js
adding itemId to facilitate componentQuery lookups
Relates to https://github.com/sonatype/nexus-bundles/pull/151
> add basic testing of the repo UI

- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/controller/Repositories.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/view/repository/RepositorySettingsForm.js
- plugins/rapture/nexus-rapture-plugin/src/main/resources/static/rapture/NX/util/condition/IsPermitted.js
https://issues.sonatype.org/browse/NEXUS-8772
> [NEXUS-8772] Use a setter instead of directly update private properties

- plugins/rapture/nexus-coreui-plugin/src/main/java/org/sonatype/nexus/coreui/RoleXO.groovy
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/view/role/RoleSettingsForm.js
- plugins/rapture/nexus-coreui-plugin/src/test/java/org/sonatype/nexus/coreui/RoleXOTest.groovy
https://issues.sonatype.org/browse/NEXUS-8726
http://bamboo.s/browse/NX3-OSSF420-1
> Nexus 8726 self referential security role fix

- testsuite/modern-testsuite/src/test/java/org/sonatype/nexus/testsuite/nuget/NugetHostedIT.java
An integration test to ensure that the link returned in the package metadata contains a usable URL to the package.
https://issues.sonatype.org/browse/NEXUS-8791
> NEXUS-8791 integration test for URL encoded ODATA package queries

- components/nexus-blobstore-api/src/main/java/org/sonatype/nexus/blobstore/api/BlobStoreManager.java
- components/nexus-core/src/main/java/org/sonatype/nexus/internal/blobstore/BlobStoreManagerImpl.java
- components/nexus-core/src/test/java/org/sonatype/nexus/internal/blobstore/BlobStoreManagerImplTest.groovy
https://issues.sonatype.org/browse/NEXUS-8705
> [NEXUS-8705] Eagerly create default blob store

- components/nexus-common/src/main/java/org/sonatype/nexus/common/stateguard/StateGuardLifecycleSupport.java
- components/nexus-core/src/main/java/org/sonatype/nexus/internal/blobstore/BlobStoreManagerImpl.java
- components/nexus-mime/src/main/java/org/sonatype/nexus/mime/MimeRule.java
- components/nexus-mime/src/test/java/org/sonatype/nexus/mime/internal/DefaultMimeSupportTest.java
- components/nexus-repository/src/main/java/org/sonatype/nexus/repository/group/GroupHandler.java
- components/nexus-repository/src/main/java/org/sonatype/nexus/repository/storage/Component.java
- components/nexus-repository/src/main/java/org/sonatype/nexus/repository/view/Content.java
- components/nexus-repository/src/main/java/org/sonatype/nexus/repository/view/Payload.java
- components/nexus-repository/src/test/java/org/sonatype/nexus/repository/storage/StorageFacetImplIT.java
- plugins/basic/nexus-quartz-plugin/src/main/java/org/sonatype/nexus/quartz/internal/nexus/NexusTaskFuture.java
- plugins/basic/nexus-quartz-plugin/src/test/java/org/sonatype/nexus/quartz/SleeperTask.java
- plugins/basic/nexus-quartz-plugin/src/test/java/org/sonatype/nexus/quartz/UpdatingTasksIT.java
- plugins/basic/nexus-quartz-plugin/src/test/java/org/sonatype/nexus/quartz/internal/nexus/NexusScheduleConverterTest.java
- plugins/basic/nexus-repository-maven/src/main/java/org/sonatype/nexus/repository/maven/MavenFacet.java
- plugins/basic/nexus-repository-maven/src/main/java/org/sonatype/nexus/repository/maven/internal/DigestExtractor.java
- plugins/basic/nexus-repository-maven/src/test/java/org/sonatype/nexus/repository/maven/internal/maven2/Maven2MetadataMergerTest.java
- plugins/basic/nexus-repository-nuget/src/main/java/com/sonatype/nexus/repository/nuget/internal/proxy/NugetProxyGalleryFacet.java
- plugins/internal/nexus-atlas-plugin/src/main/java/org/sonatype/nexus/atlas/internal/FlushableZipOutputStream.java
- plugins/security/nexus-ldap-plugin/src/main/java/org/sonatype/nexus/ldap/internal/realms/EnterpriseLdapManager.java
- plugins/security/nexus-ldap-plugin/src/main/java/org/sonatype/nexus/ldap/internal/realms/LdapConnectionUtils.java
- testsuite/modern-testsuite/src/test/java/org/sonatype/nexus/testsuite/maven/metadata/MavenRebuildMetadataIT.java
- testsuite/modern-testsuite/src/test/java/org/sonatype/nexus/testsuite/security/SimpleSessionCookieIT.java
> Removed unused imports

- plugins/internal/nexus-wonderland-plugin/src/main/java/org/sonatype/nexus/wonderland/rest/AuthenticateResource.java
make it easier to diagnose username mismatch errors
https://issues.sonatype.org/browse/NEXUS-8821
> NEXUS-8821 - improve logging for failed auth token request

- components/nexus-core/src/main/java/org/sonatype/nexus/maven/tasks/DefaultSnapshotRemover.java
https://issues.sonatype.org/browse/NEXUS-8724
we have already tested the performance improvements of the 2.11.1-01 version of this port:
https://github.com/sonatype/nexus-oss/blob/nexus-2.11.1-01-snapshot_remover_optimizations
> NEXUS-8724 snapshot remover performance improvements

- components/nexus-repository/src/main/java/org/sonatype/nexus/repository/search/SearchService.java
- components/nexus-repository/src/main/java/org/sonatype/nexus/repository/search/SearchServiceImpl.java
- components/nexus-repository/src/main/resources/org/sonatype/nexus/repository/search/elasticsearch-mapping.json
- plugins/rapture/nexus-coreui-plugin/src/main/java/org/sonatype/nexus/coreui/SearchComponent.groovy
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/store/SearchResult.js
https://issues.sonatype.org/browse/NEXUS-8846
> [NEXUS-8846] Implement search results sorting as remote sorting via Elastic

- plugins/internal/nexus-wonderland-plugin/src/main/java/org/sonatype/nexus/wonderland/rest/AuthenticateResource.java
make it easier to diagnose username mismatch errors
https://issues.sonatype.org/browse/NEXUS-8821
port of https://github.com/sonatype/nexus-oss/pull/1430
> NEXUS-8821 improve logging of auth token denials

- components/nexus-repository/src/main/java/org/sonatype/nexus/repository/storage/MetadataNode.java
- components/nexus-repository/src/main/java/org/sonatype/nexus/repository/storage/MetadataNodeEntityAdapter.java
- components/nexus-repository/src/main/java/org/sonatype/nexus/repository/storage/StorageTxImpl.java
http://bamboo.s/browse/NX3-OSSF451-2
> resolve compiler warnings

- components/nexus-core/src/main/java/org/sonatype/nexus/internal/app/NxApplication.java
- simple log message using jodatime for formatting
https://issues.sonatype.org/browse/NEXUS-8850
> NEXUS-8850 add uptime log message on shutdown

- buildsupport/rest/pom.xml
- components/nexus-core/pom.xml
- components/nexus-core/src/main/java/org/sonatype/nexus/internal/web/ErrorPageServlet.java
Cleaned up the code around `errorName` which was never getting set.
> ErrorPageServlet cleanup compiler warnings

- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/controller/Search.js
https://issues.sonatype.org/browse/NEXUS-8559
> NEXUS-8559 disable search criteria menu items instead of hiding them

- plugins/rapture/nexus-coreui-plugin/src/main/java/org/sonatype/nexus/coreui/ComponentComponent.groovy
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/app/PluginStrings.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/controller/Assets.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/view/component/AssetInfo.js
- add ability to delete an asset from the UI
https://issues.sonatype.org/browse/NEXUS-8255
http://bamboo.s/browse/NX3-OSSF470-1
> NEXUS-8255 - Browse UI - Asset Detail Page

- plugins/basic/nexus-repository-nuget/src/main/java/com/sonatype/nexus/repository/nuget/internal/proxy/NugetFeedFetcher.java
More sonar-prompted simplification
http://bamboo.s/browse/NX3-OSSF475-1 :white_check_mark:
> Breaking apart complex method

- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/view/support/Metrics.js
- testsuite/functional-testsuite/src/test/ft-resources/testsuite-oss/harness.js
- testsuite/functional-testsuite/src/test/ft-resources/testsuite-oss/support/support_metrics.t.js
- testsuite/functional-testsuite/src/test/java/org/sonatype/nexus/testsuite/SupportIT.java
https://issues.sonatype.org/browse/NEXUS-8900
Replaces: https://github.com/sonatype/nexus-oss/pull/1483
> NEXUS-8900 metrics functional tests

- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/view/support/SysInfo.js
- testsuite/functional-testsuite/src/test/ft-resources/testsuite-oss/harness.js
- testsuite/functional-testsuite/src/test/ft-resources/testsuite-oss/support/support_sysinfo.t.js
https://issues.sonatype.org/browse/NEXUS-8902
Replaces: https://github.com/sonatype/nexus-oss/pull/1484
> NEXUS-8902 system information functional tests

- components/nexus-core/src/main/java/org/sonatype/nexus/internal/security/model/OrientSecurityConfigurationSource.java
Remove caching security configuration that was in place to avoid going to db to many times. Yet the implementation is wrong as it is not thread safe and it also does not keep track of version field.
Will optimise later if necessary.
https://issues.sonatype.org/browse/NEXUS-8824
http://bamboo.s/browse/NX3-OSSF505
> [NEXUS-8824] Remove caching security configuration

- buildsupport/db/pom.xml
https://github.com/orientechnologies/orientdb/issues?q=is%3Aissue+milestone%3A2.1-rc5+is%3Aclosed
This is potentially the last RC before 2.1 goes GA.
http://bamboo.s/browse/NX3-OSSF518-1
> Update to OrientDB 2.1-rc5

- testsuite/functional-testsuite/src/test/ft-resources/testsuite-oss/harness.js
- testsuite/functional-testsuite/src/test/ft-resources/testsuite-oss/support/support_zip.t.js
https://issues.sonatype.org/browse/NEXUS-8904
> NEXUS-8904 support zip functional tests

- components/nexus-core/src/main/java/org/sonatype/nexus/NxApplication.java
https://issues.sonatype.org/browse/NEXUS-8850
> NEXUS-8850 log uptime at Nexus shutdown initialization

- assemblies/nexus-bundle-template/src/main/resources/content/conf/logback-access.xml
https://issues.sonatype.org/browse/NEXUS-8920
> NEXUS-8920 rename archived request log to be sane

- plugins/npm/nexus-npm-repository-plugin/src/main/java/com/bolyuba/nexus/plugin/npm/service/internal/orient/OrientMetadataStoreLifecycle.java
- plugins/npm/pom.xml
https://issues.sonatype.org/browse/NEXUS-8849
sanity logging and try/catch in case something goes wrong stopping metadata store
> NEXUS-8849 logging and try/catch for orient npm database stoppage

- plugins/npm/pom.xml
https://github.com/orientechnologies/orientdb/issues?q=milestone%3A2.0.12
Also includes fix for https://github.com/orientechnologies/orientdb/issues/4441
http://bamboo.s/browse/NX-OSSF1095-1 :white_check_mark:
> Update OrientDB to 2.0.12

- testsuite/functional-testsuite/src/test/ft-resources/testsuite-oss/harness.js
- testsuite/functional-testsuite/src/test/ft-resources/testsuite-oss/security/security_ssl_certificates.t.js
https://issues.sonatype.org/browse/NEXUS-8907
http://bamboo.s/browse/NX3-OSSF535
> NEXUS-8907 - SSL Certificates Functional Tests

- assemblies/nexus-base-template/src/main/resources/overlay/etc/logback.xml
- assemblies/nexus-base-template/src/main/resources/overlay/etc/system.properties
- plugins/internal/nexus-atlas-plugin/src/main/java/org/sonatype/nexus/atlas/internal/customizers/LogCustomizer.groovy
To help with refactoring the logging archive names
> Remove karaf.log system property

- plugins/basic/nexus-ui-extjs3-plugin/src/main/resources/static/js/repoServer/resources.js
Minor helptext refinement.
https://issues.sonatype.org/browse/NEXUS-8656
> [NEXUS-8656] refine non-proxy hosts helptext

- plugins/basic/nexus-logging-plugin/src/main/java/org/sonatype/nexus/logging/rest/LoggersResource.java
- plugins/basic/nexus-logging-plugin/src/main/resources/static/js/Nexus/logging/view/Add.js
https://issues.sonatype.org/browse/NEXUS-8885
> [NEXUS-8885] Add UI validator for logger name, and backend precondition

- testsuite/functional-testsuite/src/test/ft-resources/testsuite-oss/harness.js
- testsuite/functional-testsuite/src/test/ft-resources/testsuite-oss/support/support_logging.t.js
https://issues.sonatype.org/browse/NEXUS-8908
http://bamboo.s/browse/NX3-OSSF508
> NEXUS-8908 support logging functional tests

- components/nexus-core/src/main/java/org/sonatype/nexus/proxy/storage/remote/httpclient/HttpClientRemoteStorage.java
- plugins/npm/nexus-npm-repository-plugin/src/main/java/com/bolyuba/nexus/plugin/npm/service/internal/proxy/HttpProxyMetadataTransport.java
- plugins/npm/nexus-npm-repository-plugin/src/main/java/com/bolyuba/nexus/plugin/npm/service/tarball/internal/HttpTarballTransport.java
https://issues.sonatype.org/browse/NEXUS-8837
> [NEXUS-8837] Add response status line to remote.storage.outbound

- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/controller/Assets.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/view/component/AssetInfo.js
- testsuite/functional-testsuite/src/test/ft-resources/testsuite-oss/support/support_logging.t.js
https://issues.sonatype.org/browse/NEXUS-8935
http://bamboo.s/browse/NX3-OSSF553-1
> Nexus 8935 delete asset perms

- testsuite/functional-testsuite/src/test/ft-resources/testsuite-oss/framework/signin_signout.t.js
- apply bdd style to test and add explicit checks for confirmation messages
> Signin/out BDD refactor

- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/controller/Browse.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/controller/Capabilities.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/controller/Privileges.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/controller/Repositories.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/controller/Search.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/view/browse/BrowseFeature.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/view/search/SearchFeature.js
- plugins/rapture/nexus-rapture-plugin/src/main/resources/static/rapture/NX/controller/Drilldown.js
Replace custom setting of breadcrumb icon with looking up the first column and using the icon class
> Simplify setting of breadcrumb icon based on first column

- plugins/rapture/nexus-rapture-plugin/src/main/resources/static/rapture/NX/controller/dev/Logging.js
- plugins/rapture/nexus-rapture-plugin/src/main/resources/static/rapture/NX/view/dev/Logging.js
Hopefully make it somewhat easier to share UI logs like https://gist.github.com/kellyrob99/349170539fe8754527c5
> dump selected messages in the dev console log to json

- testsuite/functional-testsuite/src/test/ft-resources/testsuite-oss/framework/signin_signout.t.js
- testsuite/functional-testsuite/src/test/ft-resources/testsuite-oss/repository/repository_crud.t.js
- testsupport/nexus-siestajs-testsupport/src/main/resources/ft-overlay/testsuite-lib/NX/TestClass.js
as we're still seeing race conditions checking on message delivery
http://bamboo.s/browse/NX3-OSSF590-1
> add method to wait for a spy to be called

- testsuite/functional-testsuite/src/test/ft-resources/testsuite-oss/repository/blobstore_crud.t.js
- testsuite/functional-testsuite/src/test/ft-resources/testsuite-oss/repository/repository_crud.t.js
- testsuite/functional-testsuite/src/test/ft-resources/testsuite-oss/search/search_basic.t.js
- testsuite/functional-testsuite/src/test/ft-resources/testsuite-oss/security/security_role.t.js
- testsuite/functional-testsuite/src/test/ft-resources/testsuite-oss/security/security_user.t.js
- testsuite/functional-testsuite/src/test/ft-resources/testsuite-oss/system/system_capabilities.t.js
- testsuite/functional-testsuite/src/test/ft-resources/testsuite-oss/system/system_tasks.t.js
- testsuite/functional-testsuite/src/test/script/prepare_SearchIT.sh
- testsuite/functional-testsuite/src/test/script/prepare_siestajs.groovy
- testsupport/nexus-siestajs-testsupport/src/main/resources/ft-overlay/testsuite-lib/NX/TestClass.js
Attempting to make SearchFT more stable, along with standardization of store load and introduction of helpers for capturing screen state on CI for diagnostics. Also added an additional Bamboo artifact for capturing screenshots taken by phantomjs for review.
> FT cleanup

- components/nexus-cache/pom.xml
- thirdparty-bundles/ehcache/pom.xml
Alternative to https://github.com/sonatype/nexus-oss/pull/1619 which is closer to the original approach.
http://bamboo.s/browse/NX3-OSSF626-1 :white_check_mark:
> Clean-up generation of reduced ehcache bundle
