sonatype/nexus-oss

- plugins/rubygem/nexus-ruby-tools/src/main/resources/nexus/gem_runner.rb
- testsuite/modern-testsuite/src/test/java/org/sonatype/nexus/testsuite/ruby/GemLifecycleIT.java
using the gem command line tools is tricky since they keep state between the
execution of commands. this patch reduces the impact of this caching on the ITs.
fixes https://github.com/jruby/jruby/issues/2343
> prepare the ITs test suite to work with Rubygems version 2.4.5

- components/nexus-scheduling/src/main/java/org/sonatype/nexus/scheduling/internal/ThreadPoolTaskExecutorSPI.java
As the executor entered call method of ThreadPoolTaskInfo
before runIt was invoked to set values. And all that because
of the future.
Now future is moved out to separate map.
http://bamboo.s/browse/NX-OSSF469
> NPE fix for TP TaskExecutor

- plugins/rapture/nexus-coreui-plugin/src/main/java/org/sonatype/nexus/coreui/PrivilegeComponent.groovy
Target privileges have both 'repositoryId' and 'repositoryGroupId' as fields,
but only one will have a non-null value. Both fields map to the same property
in the XO object, so make sure we don't overwrite the non-null value with the
null value when preparing the target privilege for transfer.
This fixes the SecurityIT functional test which fails with Java8 due to differences
in the ordering of fields when mapping the internal object to the transfer object.
Diff ignoring whitespace: https://github.com/sonatype/nexus-oss/pull/948/files?w=1
http://bamboo.s/browse/NX-OSSF477-1 :white_check_mark:
> Fix target privilege XO

- components/nexus-scheduling/src/main/java/org/sonatype/nexus/scheduling/TaskConfiguration.java
- components/nexus-scheduling/src/main/java/org/sonatype/nexus/scheduling/TaskRemovedException.java
- components/nexus-scheduling/src/main/java/org/sonatype/nexus/scheduling/internal/DefaultTaskScheduler.java
- plugins/basic/nexus-quartz-plugin/src/main/java/org/sonatype/nexus/quartz/internal/QuartzSupportImpl.java
- plugins/basic/nexus-quartz-plugin/src/main/java/org/sonatype/nexus/quartz/internal/nexus/NexusTaskFuture.java
- plugins/basic/nexus-quartz-plugin/src/main/java/org/sonatype/nexus/quartz/internal/nexus/NexusTaskInfo.java
- plugins/basic/nexus-quartz-plugin/src/main/java/org/sonatype/nexus/quartz/internal/nexus/NexusTaskJobListener.java
- plugins/basic/nexus-quartz-plugin/src/main/java/org/sonatype/nexus/quartz/internal/nexus/NexusTaskJobSupport.java
- plugins/basic/nexus-quartz-plugin/src/main/java/org/sonatype/nexus/quartz/internal/nexus/QuartzTaskExecutorSPI.java
Logging revisited. Introduced "logging name" of task based
on it's configuration to make it more user friendly than
UUID (actually two UUIDs, one for NX Task and one for QZ Job!)
Also, simplified logging (ie. using "Task" instead of "NX Task", etc).
UUID should NOT appear in logs if loggers at INFO level. Still, at DEBUG
and TRACE they ARE logged, to be able to identify them in case of DB dump
analysis.
Also, removed one unused method from QuartzTaskExecutorSPI.
Issue
https://issues.sonatype.org/browse/NEXUS-7802
CI
http://bamboo.s/browse/NX-OSSF476
> NEXUS-7802: Revisit logging, Take 2

- plugins/basic/nexus-content-plugin/src/main/java/org/sonatype/nexus/content/internal/ContentServlet.java
- testsuite/modern-testsuite/src/test/java/org/sonatype/nexus/testsuite/content/range/ContentRangeIT.java
https://issues.sonatype.org/browse/NEXUS-7903
http://bamboo.s/browse/NX-OSSF483-2 :white_check_mark: 
* a range request of 0-0 should return one byte
* implicit range boundary should be length-1
* the satisfiable range should be [0..length-1]
Please check carefully against http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.16
> nexus-2.11.x [NEXUS-7903] fix content-range algorithm

- assemblies/nexus-base-edition/src/main/feature/feature.xml
- buildsupport/db/pom.xml
- pom.xml
http://bamboo.s/browse/NX-OSSF484-1
2.0-rc2 includes fixes to OSGi metadata in orient-graphdb meaning we can drop our local workaround.
> Upgrade OrientDB to 2.0-rc2

- assemblies/nexus-base-edition/src/main/feature/feature.xml
- components/nexus-extender/src/main/java/org/sonatype/nexus/extender/modules/ValidationInterceptor.java
- pom.xml
https://issues.sonatype.org/browse/NEXUS-7911
http://bamboo.s/browse/NX-OSSF486-1 :white_check_mark: 
The javax.el factory assumes its implementation will be visible from the TCCL:
* Made javax.el implementation bundle a fragment of hibernate-validator
* Switched validation-api to be fragment of hibernate-validator instead of vice-versa
* Used hibernate-validator as the TCCL during validation interception
This makes sure that the service loader lookup in validation-api can see the
hibernate-validator implementation (as they're still merged in the same space)
but also that the javax.el implementation can now be seen from the same TCCL.
> NEXUS-7911: fix javax.el discovery

- plugins/basic/nexus-content-plugin/src/main/java/org/sonatype/nexus/content/internal/ContentAuthenticationFilter.java
https://issues.sonatype.org/browse/NEXUS-7889
http://bamboo.s/browse/NX-OSSF490
Applied same logic as in NexusAuthenticationFilter in order to support RUT Auth. 
If content is protected (user token enabled and protects content), RUT auth is skipped (will work as before).
Manually ran user token UT/ITs and they all pass.
> [2.11.x] Support RUT Auth on /content URL's

- assemblies/nexus-base-edition/src/main/feature/feature.xml
This will merge their classpaths at runtime and allow graph
functions to be seen by the ServiceRegistry code in core.
(this is easier than re-working the OrientDB registry code.)
http://bamboo.s/browse/NX-OSSF499-1 :white_check_mark:
> Turn OrientDB graph bundle into a fragment of orientdb-core.

- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/view/capability/CapabilityAbout.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/view/capability/CapabilityStatus.js
https://issues.sonatype.org/browse/NEXUS-7854
CapabilityStatus was not really necessary to be changed but the panel is same as about
> Proper render About in Capabilities New

- buildsupport/groovy/pom.xml
- plugins/capabilities/nexus-capabilities-plugin/src/main/java/org/sonatype/nexus/capability/internal/ui/CapabilityComponent.groovy
- plugins/rapture/nexus-coreui-plugin/src/main/java/org/sonatype/nexus/coreui/GeneralSettingsComponent.groovy
- plugins/rapture/nexus-coreui-plugin/src/main/java/org/sonatype/nexus/coreui/HttpSettingsComponent.groovy
- plugins/rapture/nexus-coreui-plugin/src/main/java/org/sonatype/nexus/coreui/MavenUploadComponent.groovy
- plugins/rapture/nexus-coreui-plugin/src/main/java/org/sonatype/nexus/coreui/PrivilegeComponent.groovy
- plugins/rapture/nexus-coreui-plugin/src/main/java/org/sonatype/nexus/coreui/RepositoryComponent.groovy
- plugins/rapture/nexus-coreui-plugin/src/main/java/org/sonatype/nexus/coreui/RepositoryTargetComponent.groovy
- plugins/rapture/nexus-coreui-plugin/src/main/java/org/sonatype/nexus/coreui/RoleComponent.groovy
- plugins/rapture/nexus-coreui-plugin/src/main/java/org/sonatype/nexus/coreui/SmtpSettingsComponent.groovy
- plugins/rapture/nexus-coreui-plugin/src/main/java/org/sonatype/nexus/coreui/TaskComponent.groovy
- plugins/rapture/nexus-coreui-plugin/src/main/java/org/sonatype/nexus/coreui/UserComponent.groovy
- plugins/security/nexus-ldap-plugin/src/main/java/org/sonatype/security/realms/ldap/internal/ui/LdapServerComponent.groovy
- pom.xml
Upgrade groovy to newer version as only groovy 2.8+ is actually workable in Java8, although earlier versions may/may not work depending on what you're tyring to do (among other reasons to upgrade).
Challenges:
- resolution of visible fields/methods has changed, leading to problems where Guice intercepted methods with Closures calling private methods can no longer find them
Options:
- @CompileStatic code does not appear to suffer from the lookup problem, but forces us to abandon some of the Groovier syntax and dynamic typing features. Also, it too seems to have some strange buggy behaviour, like the GDK method lookup failure explicitly mentioned later
- remote private modifier from affected methods and apply @PackageScope to keep the visibility as tight as possible
@PackageScope option …
> NEXUS-7901 groovy upgrade

- components/nexus-core/src/main/java/org/sonatype/nexus/events/DeleteRepositoryFoldersEventInspector.java
When repository is removed from the system, it's local storage
is moved to "global trash", which is in some cases undesirable.
By setting
`org.sonatype.nexus.events.DeleteRepositoryFoldersEventInspector.deletePermanently`
system property to `true` this will not happen, and folders will be
simply removed.
Test for "deleteForever" feature was added originally with task (see DeleteRepositoryFoldersTaskTest), but in NX it was never used.
CI
http://bamboo.s/browse/NX-OSSF497
> Add property to disable global trash for removed repositories

- buildsupport/other/pom.xml
- components/nexus-core/src/main/resources/org/apache/tika/mime/custom-mimetypes.xml
And remove the "hack" for MS PE files (see NEXUS-7603)
Ref
https://github.com/sonatype/nexus-oss/pull/978
Issue
https://issues.sonatype.org/browse/NEXUS-7650
CI
http://bamboo.s/browse/NX-OSSF508
> [2.11.x] NEXUS-7650: Update to tika 1.7

- plugins/rapture/nexus-rapture-plugin/src/main/resources/static/rapture/NX/controller/Menu.js
Nexus won’t start, because it can’t find certain views which have been added/deleted. This PR fixes those entries.
> Fixes the list of dependencies in the Menu controller

- plugins/rapture/nexus-coreui-plugin/src/main/java/org/sonatype/nexus/coreui/PrivilegeRepositoryTargetXO.groovy
- plugins/rapture/nexus-rapture-plugin/src/main/resources/static/rapture/NX/controller/ExtDirect.js
- allow empty values for repositoryId, which gets translated to a '*' permission element for repos
https://issues.sonatype.org/browse/NEXUS-7939
> NEXUS-7939 - Privilege add validates with incorrect message?

- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/controller/Users.js
- simply call the parent of our overloaded method to ensure the transition is triggered
- minor modifications to test case to ensure visibility on transition and speed up by entering password before moving on to the following status field
https://issues.sonatype.org/browse/NEXUS-7978
> NEXUS-7978 - User Creation does not transition back to list view after saving

- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/controller/Outreach.js
- move removal/addition of iframe to the callback to prevent doubling up due to race condition
https://issues.sonatype.org/browse/NEXUS-7817
> NEXUS-7817 - Second frame on welcome screen sometimes appears repeating milestone resources

- components/nexus-common/src/main/java/org/sonatype/nexus/common/io/DirSupport.java
In case of non-empty directory cross-volume move, the code was
incorrect, and did not fulfill contract described in method
javadoc, there was no "fallback".
Not a real PR, it has been reviewed already on 2.11.x branch. Still, as master and nexus-2.11.x branch diverged, cherry-picking the code is not simple, so just to have a sanity CI run. Will merge once CI is good.
Issue
https://issues.sonatype.org/browse/NEXUS-7933
CI
http://bamboo.s/browse/NX3-OSSF24
> NEXUS-7933: Cross Volume move ported to master

- components/nexus-extender/src/main/java/org/sonatype/nexus/extender/modules/MetricsRegistryModule.java
- components/nexus-extender/src/main/java/org/sonatype/nexus/extender/modules/NexusBundleModule.java
The new MetricsRegistryModule is automatically installed for any bundle that
imports the 'com.codahale.metrics' package. Fixes the lack of health checks
registered by the HealthCheckMediator - as no registry was explicitly bound
the mediator was never activated. Instead the HealthCheckServlet ended up
using its own instance of the registry, created via an implicit binding.
http://bamboo.s/browse/NX3-OSSF25-1
> Make the shared metrics and healthcheck registries available for injection

- components/nexus-core/src/main/java/org/sonatype/nexus/web/NexusGuiceFilter.java
Since we now always construct this filter programatically and not via web.xml
http://bamboo.s/browse/NX3-OSSF26-1
> Remove unused constructor from NexusGuiceFilter

- plugins/basic/nexus-rrb-plugin/src/main/java/org/sonatype/nexus/plugins/rrb/MavenRepositoryReader.java
Fix the connection leak in RRB. Response entity stream is not closed. Still, in "normal" cases this might go unnoticed as GC and HttpClient will gracefully handle this. But, in case of gzip content encoding, where HttpClient's ResponseContentEncoding interceptor is interfering by swapping out entity wrapped in GzipInputStream this leads to severe leak.
Issue
https://issues.sonatype.org/browse/NEXUS-8083
CI
TBD
> NEXUS-8083: Fix the connection leak in Browse Remote

- plugins/rubygem/pom.xml
with jruby-1.7.18 the scripting container which the ruby plugin uses is just
not working on windows.
trivial + review
> use jruby-1.7.19

- components/nexus-core/src/main/java/org/sonatype/nexus/log/internal/LogbackLogManager.java
Seems in 2.7 new levels were introduced, but on back-end the translation
of them did not happen correctly.
Issue
https://issues.sonatype.org/browse/NEXUS-8077
CI
http://bamboo.s/browse/NX-OSSF578
> NEXUS-8077: Fixing OFF log level for Loggers visible as TRACE in the UI

- plugins/internal/nexus-atlas-plugin/src/main/java/org/sonatype/nexus/atlas/internal/SystemInformationGeneratorImpl.groovy
In some cases IOEx is thrown by FileStore objects, that are inspecting some properties of it.
Issue
https://issues.sonatype.org/browse/NEXUS-8076
CI
http://bamboo.s/browse/NX-OSSF579
> NEXUS-8076: Ignore IOEx when gathering volume infos

- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/app/PluginStrings.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/controller/Tasks.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/view/task/TaskSelectType.js
- plugins/rapture/nexus-rapture-plugin/src/main/resources/static/rapture/NX/view/drilldown/Master.js
- incorporate existing filter into UI
https://issues.sonatype.org/browse/NEXUS-8148
Related tests are in https://github.com/sonatype/nexus-bundles/commit/7635c5ce40054936dc58dd00c4d9bcbfc84453d1
Apologies as I accidentally committed that to master first instead of https://github.com/sonatype/nexus-bundles/tree/NEXUS-8148_filterTasksUI
> NEXUS-8148 - add scheduled tasks list filter when creating tasks

- plugins/rubygem/nexus-ruby-plugin/src/main/java/org/sonatype/nexus/plugins/ruby/group/GroupNexusStorage.java
- plugins/rubygem/nexus-ruby-plugin/src/main/java/org/sonatype/nexus/plugins/ruby/proxy/DefaultProxyRubyRepository.java
- plugins/rubygem/nexus-ruby-tools/src/main/java/org/sonatype/nexus/ruby/GemRunner.java
- testsuite/modern-testsuite/src/test/java/org/sonatype/nexus/testsuite/ruby/GemLifecycleIT.java
- testsuite/modern-testsuite/src/test/java/org/sonatype/nexus/testsuite/ruby/RubyITSupport.java
treat only specs.4.8, latest_specs.4.8 and prereleased_specs.4.8 files differently
these files *.4.8 are anyways not used with client side tools and are virtual, i.e. generated
on the fly by gunzipping the *.4.8.gz files
fixes NEXUS-8144 and allows the *.gz files to expire like other volatile files.
WIP since ITs are missing
> NEXUS-8144: index files never expire (specs.4.8, latest_specs.4.8 and prereleased_specs.4.8)

- buildsupport/goodies/pom.xml
- buildsupport/testing/pom.xml
- components/nexus-bootstrap/src/main/java/org/sonatype/nexus/bootstrap/osgi/BootstrapListener.java
- components/nexus-extender/pom.xml
- components/nexus-extender/src/main/java/org/sonatype/nexus/extender/NexusContextListener.java
- pom.xml
- testsupport/nexus-pax-exam/pom.xml
- testsupport/nexus-pax-exam/src/main/java/org/sonatype/nexus/pax/exam/AbstractNexusPaxExamIT.java
- testsupport/nexus-pax-exam/src/main/java/org/sonatype/nexus/pax/exam/internal/Activator.java
- testsupport/nexus-pax-exam/src/main/java/org/sonatype/nexus/pax/exam/internal/DelayedProbeInvokerFactory.java
- testsupport/nexus-pax-exam/src/test/java/org/sonatype/nexus/pax/exam/SanityIT.java
- testsupport/pom.xml
[ depends on https://github.com/sonatype/sisu-goodies/pull/34 ]
https://issues.sonatype.org/browse/NEXUS-8092
Replacement IT support using Pax-Exam to start Nexus and wait for it to fully boot up. We can also add and remove features/bundles, and control whether the container is used per-test, per-class, or per-suite.
See https://ops4j1.jira.com/wiki/display/PAXEXAM4/Documentation for more information.
> NEXUS-8092: replacement IT support based on Pax-Exam

- plugins/yum/nexus-yum-repository-plugin/src/main/java/org/sonatype/nexus/yum/internal/task/GenerateMetadataTask.java
https://issues.sonatype.org/browse/NEXUS-8195
Move marking of a Yum group repository as dirty outside of block that we keep the UID lock to avoid deadlock between the group that has to be marked and its member repository.
> [NEXUS-8195][2.11.x] Deadlock between yum merge metadata task and yum generate metadata task

- components/nexus-core/src/main/java/org/sonatype/nexus/proxy/item/ChecksummingContentLocator.java
- components/nexus-core/src/test/java/org/sonatype/nexus/proxy/item/ChecksummingContentLocatorTest.java
Otherwise someone could wrap a re-usable content locator with `ChecksummingContentLocator` and call `getContent` a number of times fetching partial data (for example checking the header for magic numbers) before calling it one last time, consuming all the content and finally completing the hash calculation.
https://issues.sonatype.org/browse/NEXUS-8221
http://bamboo.s/browse/NX-OSSF610-1 :white_check_mark:
> NEXUS-8221: always reset message digest before starting new checksum calculation

- plugins/rapture/nexus-rapture-plugin/src/main/resources/static/rapture/NX/app/PluginStrings.js
- plugins/rapture/nexus-rapture-plugin/src/main/resources/static/rapture/NX/view/drilldown/Master.js
Issues:
https://issues.sonatype.org/browse/NEXUS-8110
https://issues.sonatype.org/browse/NEXUS-8182
@joedragons doesn’t see the copyright symbol or ellipses in his copy of Windows/IE. I wonder if the problem is that I use literals in code, rather than the HTML shorthand… `©` instead of `&copy;`, for example.
This PR tests that theory on the copyright symbol in the footer.
> Fixes a few problems with ellipses and copyright symbols on IE

- components/nexus-core/src/main/java/org/sonatype/nexus/proxy/item/ChecksumReconciler.java
- components/nexus-core/src/main/java/org/sonatype/nexus/tasks/ReconcileChecksumsTask.java
- components/nexus-core/src/main/java/org/sonatype/nexus/tasks/descriptors/ReconcileChecksumsTaskDescriptor.java
- components/nexus-core/src/test/java/org/sonatype/nexus/tasks/ReconcileChecksumsTaskTest.java
https://issues.sonatype.org/browse/NEXUS-8226
http://bamboo.s/browse/NX-OSSF635-2 :white_check_mark: 
also resets any cached remote checksums if they're also affected
> [NEXUS-8226] limit reconciliation to attributes modified since a given date

- components/nexus-repository/src/main/java/org/sonatype/nexus/repository/storage/StorageFacetImpl.java
https://issues.sonatype.org/browse/NEXUS-8249
The orient hook was called multiple times, before and after a proper RID was set on the component.
The fix will only index the component after the proper RID is set on record.
It also fixes a bug related to only acting on component records.
> [NEXUS-8249] Fix duplicate search results

- plugins/basic/nexus-repository-nuget/src/main/java/com/sonatype/nexus/repository/nuget/internal/NugetGalleryFacetImpl.java
- plugins/basic/nexus-repository-nuget/src/test/java/com/sonatype/nexus/repository/nuget/internal/NugetGalleryFacetImplPutTest.java
- store only top level attributes on the component, everything else at the Asset level
https://issues.sonatype.org/browse/NEXUS-8236
> NEXUS-8236 - Store NuGet package feed metadata at the asset level

- buildsupport/rest/pom.xml
Running sanity check under http://bamboo.s/browse/NX3-OSSF131-1/
RESTEasy release notes: https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12310560&version=12325993 and a more accurate list of actual changes: https://github.com/resteasy/Resteasy/compare/3.0.10.Final...bb2cfea2ef7f3da49ee276bb2f7fbb4130e51e76
> Test latest Siesta snapshot (brings in RESTEasy 3.0.11.Final)

- components/nexus-core/src/main/java/org/sonatype/nexus/configuration/AbstractConfigurable.java
Noticed this exception stack in a couple of the quartz ITs on CI (which didn't fail, but also didn't complete)
```
Caused by: java.lang.NullPointerException: null
at org.sonatype.nexus.configuration.AbstractConfigurable.getCurrentConfiguration(AbstractConfigurable.java:231)
at org.sonatype.nexus.configuration.DefaultGlobalRestApiSettings.isEnabled(DefaultGlobalRestApiSettings.java:65)
at org.sonatype.nexus.web.BaseUrlDetector.detect(BaseUrlDetector.java:73)
at org.sonatype.nexus.web.BaseUrlDetector.set(BaseUrlDetector.java:109)
at org.sonatype.nexus.quartz.internal.nexus.NexusTaskJobSupport.execute(NexusTaskJobSupport.java:114)
at org.sonatype.nexus.quartz.JobSupport.execute(JobSupport.java:44)
... 9 common frames omitted
```
Note: this only affects a couple of quartz tests which perform …
> Protect against potential NPE in legacy configuration code when scheduled tasks run early

- components/nexus-orient/src/main/java/org/sonatype/nexus/orient/OIndexNameBuilder.java
* Allows setting multiple properties for an index name to be used with composite keys.
* Use "_" instead of "." after type as <type>.<name> is a special meaning for Orient (http://orientdb.com/docs/last/Indexes.html)
http://bamboo.s/browse/NX3-OSSF174
> Allow creation of composite keys index names

- assemblies/nexus-base-template/src/main/resources/overlay/etc/jetty.xml
https://issues.sonatype.org/browse/NEXUS-8448
> [NEXUS-8448] Restore jetty X-Forwarded* header support

- plugins/internal/nexus-atlas-plugin/src/main/java/org/sonatype/nexus/atlas/ui/SupportZipComponent.groovy
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/app/PluginStrings.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/view/support/SupportZip.js
- plugins/rapture/nexus-rapture-plugin/src/main/resources/static/rapture/NX/app/Application.js
Also updates default ext.direct remoting provider to not retry and have 60 second timeout (instead of 30)
https://issues.sonatype.org/browse/NEXUS-8442
> [NEXUS-8442] increase timeout for support-zip generation to 3 minutes

- components/nexus-repository/src/main/java/org/sonatype/nexus/repository/proxy/ProxyFacetSupport.java
When response is non-200, it still might have entity
that reserves the connection.
Spotted this in a moment NX needed to have multiple repositories (not only maven-central), as in that case NX almost instantly depleted connPool (with 404 HTML page responses).
> Httpclient leak fix

- plugins/npm/pom.xml
To pick up the UNC path fix among others: https://github.com/orientechnologies/orientdb/issues?q=milestone%3A2.0.8+is%3Aclosed
https://issues.sonatype.org/browse/NEXUS-8389
http://bamboo.s/browse/NX-OSSF787-1 :white_check_mark:
> [nexus-2.11.x] [NEXUS-8389] Update OrientDB to 2.0.8

- components/nexus-repository/src/main/java/org/sonatype/nexus/repository/httpclient/ConnectionConfig.java
- components/nexus-repository/src/main/java/org/sonatype/nexus/repository/httpclient/HttpClientFactoryImpl.java
- plugins/basic/nexus-repository-maven/src/main/java/org/sonatype/nexus/repository/maven/internal/MavenDefaultRepositoriesContributor.groovy
- plugins/basic/nexus-repository-nuget/src/main/java/com/sonatype/nexus/repository/nuget/internal/NugetDefaultRepositoriesContributor.groovy
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/app/PluginStrings.js
https://issues.sonatype.org/browse/NEXUS-8493
The fix changes the config to use seconds instead of milliseconds, changes the defaults to 3 retries / 20 seconds timeout (this will be changed when we will take the defaults from global http config) and removes the default configuration for maven/nuget proxies.
> [NEXUS-8493] Default timeout values for proxy repositories

- plugins/basic/nexus-repository-maven/src/main/java/org/sonatype/nexus/repository/maven/internal/MavenFacetImpl.java
- plugins/basic/nexus-repository-maven/src/main/java/org/sonatype/nexus/repository/maven/internal/maven2/Maven2Format.java
- plugins/basic/nexus-repository-maven/src/main/java/org/sonatype/nexus/repository/maven/internal/maven2/Maven2GroupFacet.java
- plugins/basic/nexus-repository-maven/src/main/java/org/sonatype/nexus/repository/maven/internal/maven2/Maven2GroupMetadataHandler.java
- plugins/basic/nexus-repository-maven/src/main/java/org/sonatype/nexus/repository/maven/internal/maven2/Maven2GroupRecipe.groovy
- plugins/basic/nexus-repository-maven/src/main/java/org/sonatype/nexus/repository/maven/internal/maven2/Maven2MavenPathParser.java
Set of smaller changes and fixes.
Changes:
1) maven components has formatAttribute StorageFace.P_PATH that made no sense
2) Merging groups are specific to Maven2 format only (as repo metadata itself is), move them into maven2 package
3) centralise and expose some constants instead of litter them around as private (this is especially true for "walker" branch that uses these)
> Maven2 fixes

- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/controller/Search.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/view/search/SearchFeature.js
Issue: https://issues.sonatype.org/browse/NEXUS-7726
Before: http://take.ms/h8OEV
After: http://take.ms/ERCN1
One of the complaints in the ticket was that some of the input fields are too short for their data types. Can someone more familiar with this area update the widths of those fields? @adreghiciu or @jdillon, perhaps? Feel free to push changes to this PR.
> [NEXUS-7726] Wrap search criteria boxes

- testsupport/nexus-pax-exam/src/main/java/org/sonatype/nexus/pax/exam/NexusPaxExamSupport.java
Start karaf-based IT with debug enabled (port 5005, suspend=y) when -Dit.debug=true
http://bamboo.s/browse/NX3-OSSF250-1
> Support debugging of ITs using "it.debug" system property

- plugins/basic/nexus-repository-httpbridge/src/main/java/org/sonatype/nexus/repository/httpbridge/internal/ViewServlet.java
Exceptions get logged to the console, but cutting out AuthorizationExceptions (which makes format debugging really noisy).
> Suppressing AuthorizationExceptions in Nexus console

- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/controller/SslCertificates.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/controller/SslTrustStore.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/view/ssl/SslCertificateDetailsPanel.js
https://issues.sonatype.org/browse/NEXUS-8489
The certificate window was transformed to a panel and used as part of drill down.
> [NEXUS-8489] Bring back ssl certificate details window

- plugins/rapture/nexus-rapture-plugin/src/main/resources/static/rapture/NX/view/drilldown/Drilldown.js
https://issues.sonatype.org/browse/NEXUS-8542
The problem is that editable conditions are based on the fact that there is only one form of a certain type active when the edit panel is shown. yet, the add panels are still there but hidden, so the fix will remove the ones after the current shown one.
> [NEXUS-8542] Remove create panels when sliding panels

- plugins/rapture/nexus-coreui-plugin/src/main/java/org/sonatype/nexus/coreui/TaskComponent.groovy
- plugins/rapture/nexus-coreui-plugin/src/main/java/org/sonatype/nexus/coreui/TaskXO.groovy
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/view/task/TaskSettingsForm.js
- include cronExpression in form submit
- ensure that rejected cronExpression is matched to the right field, otherwise it shows as a transient popup that is easy to miss
https://issues.sonatype.org/browse/NEXUS-8576
http://bamboo.s/browse/NX3-OSSF271-1
Regex validated at submit:
Quartz fails due to a logical constraint:
> NEXUS-8576 - Cannot submit tasks with advanced (cron) filled in

- plugins/basic/nexus-repository-httpbridge/src/main/java/org/sonatype/nexus/repository/httpbridge/internal/describe/DescriptionRendererImpl.java
- plugins/basic/nexus-repository-httpbridge/src/main/java/org/sonatype/nexus/repository/httpbridge/internal/describe/EscapeHelper.java
- plugins/basic/nexus-repository-httpbridge/src/main/resources/org/sonatype/nexus/repository/httpbridge/internal/describe/describe.vm
https://issues.sonatype.org/browse/NEXUS-8571
Note this won't actually fix the preset master state or resolve the ?describe on /content (legacy repository framework), nor will this actually show timing information in new CMA ?describe due to https://issues.sonatype.org/browse/NEXUS-8573
>  [NEXUS-8571] escape html values when rendering description values

- plugins/basic/nexus-repository-nuget/src/main/java/com/sonatype/nexus/repository/nuget/internal/AbstractNugetHandler.java
And do not report it as internal error. ViewSerlvet change in original PR https://github.com/sonatype/nexus-oss/pull/1320 for NuGet is not enough (actually, is completely circumvented), as NuGet handles PUT requests in it's own handler along with XML error message creation for client.
Issue
https://issues.sonatype.org/browse/NEXUS-8637
CI
TBD
> NEXUS-8637: Make nuget aware if redeploy attempts

- testsuite/modern-testsuite/src/test/java/org/sonatype/nexus/testsuite/nuget/NugetITSupport.java
During an earlier PR, I added a logger to NexusPaxExamSupport, but didn't remove the redundant one from NugetITSupport. This corrects that.
> Removing redundant logger

- plugins/basic/nexus-repository-nuget/src/main/java/com/sonatype/nexus/repository/nuget/internal/NugetGalleryFacetImpl.java
- plugins/basic/nexus-repository-nuget/src/test/java/com/sonatype/nexus/repository/nuget/internal/NugetGalleryFacetImplGetTest.java
- testsuite/modern-testsuite/src/test/java/org/sonatype/nexus/testsuite/nuget/NugetProxyIT.java
Discovered during testing of: https://issues.sonatype.org/browse/NEXUS-8611
NuGet proxies need to expect that sometimes assets will exist with no blobs.
> Graceful handling of unfetched blobs

- components/nexus-repository/src/main/java/org/sonatype/nexus/repository/http/HttpResponses.java
- components/nexus-repository/src/main/java/org/sonatype/nexus/repository/proxy/ProxyFacetSupport.java
- components/nexus-repository/src/main/java/org/sonatype/nexus/repository/proxy/ProxyHandler.java
- plugins/basic/nexus-repository-nuget/src/main/java/com/sonatype/nexus/repository/nuget/internal/proxy/NugetProxyFacet.java
- testsuite/modern-testsuite/src/test/java/org/sonatype/nexus/testsuite/nuget/NugetProxyIT.java
Two things fixed:
a) Nuget had no implementation for getUrl(), so constructing a message for IOException would itself throw an exception
b) When a proxy can't fetch an uncached artifact due to IOException, it now reports HTTP 502 (bad gateway) rather than 503 (service unavailable)
> NEXUS-8749 Nuget proxy mangling remote communication errors

- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/app/PluginConfig.js
- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/controller/HealthCheckSearch.js
- hide healthcheck columns until we fully implement the feature in NX3
https://issues.sonatype.org/browse/NEXUS-8773
> NEXUS-8773 - Age and popularity broken

- buildsupport/httpclient/pom.xml
Bump to HttpClient 4.5 (client and mime is 4.5, httpcore remains 4.4.1).
Post M4
Release Notes of HttpClient 4.5
https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12310360&version=12329460
CI
http://bamboo.s/browse/NX3-OSSF402
> Bump to HttpClient 4.5

- components/nexus-core/src/main/java/org/sonatype/nexus/internal/app/BaseUrlManagerImpl.java
- components/nexus-core/src/test/java/org/sonatype/nexus/internal/app/BaseUrlManagerImplTest.java
Support encoded urls in base url detection.
Replaces: https://github.com/sonatype/nexus-oss/pull/1409
https://issues.sonatype.org/browse/NEXUS-8791
> NEXUS-8791 base url manager detect url fix

- components/nexus-core/src/main/java/org/sonatype/nexus/apachehttpclient/NexusSSLConnectionSocketFactory.java
https://issues.sonatype.org/browse/NEXUS-8823
https://issues.sonatype.org/browse/NEXUS-8856
http://bamboo.s/browse/NX-OSSF994-1 :white_check_mark: 
We have our own custom version of SSLConnectionSocketFactory which needs to pick up the same fix that was applied in https://issues.apache.org/jira/browse/HTTPCLIENT-1478
http://svn.apache.org/viewvc/httpcomponents/httpclient/branches/4.3.x/httpclient/src/main/java/org/apache/http/conn/ssl/SSLConnectionSocketFactory.java?r1=1560975&r2=1626784
> [NEXUS-8856] apply fix for HTTPCLIENT-1478 to NexusSSLConnectionSocketFactory

- plugins/rapture/nexus-coreui-plugin/src/main/java/org/sonatype/nexus/coreui/TaskComponent.groovy
Removed the default cases in the task description function in favor of covering all the possible cases based on the enums.
https://issues.sonatype.org/browse/NEXUS-8857
http://bamboo.s/browse/NX3-OSSF455-1
> NEXUS-8857 removed default in favor of covering all enum values

- plugins/basic/nexus-repository-nuget/src/main/java/com/sonatype/nexus/repository/nuget/internal/proxy/NugetFeedFetcher.java
- plugins/basic/nexus-repository-nuget/src/main/java/com/sonatype/nexus/repository/nuget/internal/proxy/NugetProxyGalleryFacet.java
When an upstream repository returns a non-200 status code, the Nuget proxy can throw an NPE internally and potentially leak http connections.
> Eliminate possible NPE in NuGet proxy

- plugins/npm/pom.xml
There isn't a specific issue that requires us to upgrade for our embedded use-case (and any change implies additional testing) but the following changes suggest we might want to consider upgrading:
https://github.com/orientechnologies/orientdb/issues?q=milestone%3A2.0.10
https://github.com/orientechnologies/orientdb/issues?q=milestone%3A2.0.11
http://bamboo.s/browse/NX-OSSF1010-1 :white_check_mark:
> [nexus-2.11.x] Update OrientDB to 2.0.11

- plugins/pom.xml
- plugins/rapture/nexus-rapture-plugin/src/main/resources/static/rapture/NX/Assert.js
- plugins/rapture/nexus-rapture-plugin/src/main/resources/static/rapture/NX/Permissions.js
related: https://github.com/sonatype/nexus-pro/pull/567
will log an error if boolean expression doesn't eval to true, not throwing exceptions as that messes up the entire app.
adds a omission flag to compile this out of the app.
> Add NX.Assert and support for //<if assert> omission

- assemblies/nexus-bundle-template/src/main/resources/content/conf/logback-access.xml
https://issues.sonatype.org/browse/NEXUS-8913
common format + elapsedTime
made the pattern tokens verbose to avoid the inevitable browsing of logback-access docs or explaining to end user what the single letter tokens mean
WIP because not officially in a sprint yet
> NEXUS-8913 add elapsed time to request log

- plugins/rapture/nexus-rapture-plugin/src/main/resources/static/rapture/NX/controller/Message.js
Mostly so functional tests can do something like the following to control the timings associated with message windows.
```
Ext.merge(t.controller('Message').windowOptions, {
slideInDuration: 200,
slideBackDuration: 200,
autoCloseDelay: 300,
});
```
> Make Message windowOptions available for internal customization

- plugins/rapture/nexus-rapture-plugin/src/main/resources/static/rapture/NX/app/Application.js
- plugins/rapture/nexus-rapture-plugin/src/main/resources/static/rapture/NX/app/Loader.js
- testsuite/functional-testsuite/src/test/ft-resources/testsuite-oss/harness.js
- testsupport/nexus-siestajs-testsupport/src/main/resources/ft-overlay/testsuite-lib/NX/TestClass.js
- testsupport/nexus-siestajs-testsupport/src/main/resources/ft-overlay/testsuite-lib/NX/TestHarness.js
This should help improve reliability of tests, and also fixes issue to allow timeouts to be configured properly on group/test or harness.
> Add rapture app ready event and other siesta-js refinements

- plugins/rapture/nexus-coreui-plugin/src/main/resources/static/rapture/NX/coreui/controller/HealthCheckColumns.js
- plugins/rapture/nexus-rapture-plugin/src/main/resources/static/rapture/NX/app/Application.js
- plugins/rapture/nexus-rapture-plugin/src/main/resources/static/rapture/NX/ext/direct/RemotingProvider.js
This allows us to avoid buffering of health check calls with other calls like getting search results or components to be browsed. 
http://bamboo.s/browse/NX3-OSSF547
> Make possible to avoid buffering of Ext.Direct calls

- assemblies/nexus-base-template/src/main/resources/overlay/etc/logback.xml
- components/nexus-core/src/main/resources/org/sonatype/nexus/internal/log/logback-nexus.xml
make the same as recent request log changes.
Do not plan to make this change in 2.11.x unless team insists - worried about the fact this has been this way too long in nexus 2.x
trivial in theory and didn't want to forget about it due to recent request log changes.
> NEXUS-8944 nexus archive log names

- testsuite/functional-testsuite/src/test/ft-resources/testsuite-oss/system/http_configuration.t.js
spy on Message to assert confirmation messages in the UI
> re-enable message confirmation test 

- plugins/rapture/nexus-rapture-plugin/src/main/resources/static/rapture/NX/controller/dev/Logging.js
- plugins/rapture/nexus-rapture-plugin/src/main/resources/static/rapture/NX/view/dev/Logging.js
Instead of dumping JSON encoded selection to console, open a window and render something easier to comprehend and also selectable to copy into whatever.
https://www.evernote.com/l/ABJgL9eOoRtDoqVf_gCD3xJEJFWYEum79s0
> Refine logging dump to an export to window

- components/nexus-httpclient/src/main/java/org/sonatype/nexus/httpclient/config/NonProxyHosts.java
- components/nexus-httpclient/src/main/java/org/sonatype/nexus/httpclient/config/NonProxyHostsValidator.java
- components/nexus-httpclient/src/test/java/org/sonatype/nexus/httpclient/config/NonProxyHostsValidatorTest.groovy
- plugins/rapture/nexus-coreui-plugin/src/main/java/org/sonatype/nexus/coreui/HttpSettingsXO.groovy
https://issues.sonatype.org/browse/NEXUS-8981
http://bamboo.s/browse/NX3-OSSF597-2 :white_check_mark: 
Note this leaves the existing annotation in place at https://github.com/sonatype/nexus-oss/blob/master/components/nexus-httpclient/src/main/java/org/sonatype/nexus/httpclient/config/ProxyConfiguration.java#L38 for when we enable validation in HttpClientManagerImpl
> [NEXUS-8981] apply NonProxyHost validation to XO

- plugins/rapture/nexus-rapture-plugin/src/main/resources/static/rapture/NX/controller/dev/Developer.js
- plugins/rapture/nexus-rapture-plugin/src/main/resources/static/rapture/NX/controller/dev/Stores.js
- plugins/rapture/nexus-rapture-plugin/src/main/resources/static/rapture/NX/view/dev/Tests.js
Add smarter rendering of values in dev panel store browser:
https://www.evernote.com/l/ABKm4-1qcQNK7rxlPV8oWrrjtKegb73semc
Some stores have fields which don't Ext.encode well, like the NX.store.dev.Condition store, but this change should only log an error and not fux the UI:
https://www.evernote.com/l/ABIq-_MQAK5LiLL9a4IYVL8T9lYwMC5cQXA
Add option to clear the local state:
https://www.evernote.com/l/ABLXEuR7pR1CCYVRoF55FBh_tNCt3Nb48v8
https://www.evernote.com/l/ABL5oE8X35FFb5RACNWM8ObXfht3IH3l0fo
> Few refinements to dev panel

- components/nexus-repository/src/main/java/org/sonatype/nexus/repository/cache/CacheController.java
- components/nexus-repository/src/main/java/org/sonatype/nexus/repository/group/GroupFacetImpl.java
- components/nexus-repository/src/main/java/org/sonatype/nexus/repository/proxy/ProxyFacetSupport.java
- plugins/basic/nexus-repository-maven/src/main/java/org/sonatype/nexus/repository/maven/internal/maven2/Maven2GroupFacet.java
- testsuite/modern-testsuite/src/test/java/org/sonatype/nexus/testsuite/maven/metadata/MavenMergeMetadataIT.java
Alternative to #1579 which removes persistence of cache tokens and enables caching logic for all groups (currently only used in Maven groups). The cache token check also now takes precedence over ageing, as in Nexus 2. 
Verified that rebooting does not force regeneration of the merged Maven2 metadata, because the cache token starts off as `null`. Only when the members (or their order) change is the cache token invalidated and regeneration of the merged metadata may occur.
Note that ageing is not enabled for groups, because it's expected that the cache will be invalidated by other means when there's a change in member content. For Maven2 asset events trigger the merged metadata to be evicted from the cache, in addition to the members check in the generic group facet.
> Add caching logic to groups, invalidate the cache when the members change
